Importing Libraries

In [2]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import NearestNeighbors
from difflib import get_close_matches

EDA

In [3]:
df=pd.read_csv("dataset.csv")

In [4]:
df.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [5]:
df.shape

(10000, 9)

In [6]:
df.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

Handling Missing Values

In [7]:
df["overview"]=df["overview"].fillna('')
df["genre"]=df["genre"].fillna('')

df.isnull().sum()

id                   0
title                0
genre                0
original_language    0
overview             0
popularity           0
release_date         0
vote_average         0
vote_count           0
dtype: int64

Feature Selection

In [8]:
df["tags"]= df["genre"] + " : " + df["overview"]
df.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,tags
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,"Drama,Crime : Framed in the 1940s for the doub..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,"Comedy,Drama,Romance : Raj is a rich, carefree..."
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,"Drama,Crime : Spanning the years 1945 to 1955,..."
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,"Drama,History,War : The true story of how busi..."
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,"Drama,Crime : In the continuing saga of the Co..."

In [9]:
movies=df[['id', 'title', 'genre', 'overview', 'tags']].copy()
movies.drop(columns=["genre","overview"])

,id,title,tags
0,278,The Shawshank Redemption,"Drama,Crime : Framed in the 1940s for the doub..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance : Raj is a rich, carefree..."
2,238,The Godfather,"Drama,Crime : Spanning the years 1945 to 1955,..."
3,424,Schindler's List,"Drama,History,War : The true story of how busi..."
4,240,The Godfather: Part II,"Drama,Crime : In the continuing saga of the Co..."
...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy : The story follows t..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventu..."
9997,13995,Captain America,"Action,Science Fiction,War : During World War ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama : A man named F..."
9999,455957,Domino,"Thriller,Action,Crime : Seeking justice for hi..."

In [10]:
movies.head()

,id,title,genre,overview,tags
0,278,The Shawshank Redemption,"Drama,Crime",Framed in the 1940s for the double murder of h...,"Drama,Crime : Framed in the 1940s for the doub..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance","Raj is a rich, carefree, happy-go-lucky second...","Comedy,Drama,Romance : Raj is a rich, carefree..."
2,238,The Godfather,"Drama,Crime","Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime : Spanning the years 1945 to 1955,..."
3,424,Schindler's List,"Drama,History,War",The true story of how businessman Oskar Schind...,"Drama,History,War : The true story of how busi..."
4,240,The Godfather: Part II,"Drama,Crime",In the continuing saga of the Corleone crime f...,"Drama,Crime : In the continuing saga of the Co..."

Text data to feature vectors

In [11]:
cv = CountVectorizer(max_features=10000, stop_words='english')
vector = cv.fit_transform(movies['tags'].values.astype('U'))

In [12]:
print(vector)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 237342 stored elements and shape (10000, 10000)>
  Coords	Values
  (0, 2738)	1
  (0, 2153)	1
  (0, 3683)	1
  (0, 34)	1
  (0, 2712)	1
  (0, 5975)	1
  (0, 9807)	1
  (0, 5427)	1
  (0, 848)	1
  (0, 456)	1
  (0, 938)	1
  (0, 6111)	1
  (0, 5293)	1
  (0, 6942)	2
  (0, 7111)	1
  (0, 8233)	1
  (0, 9896)	1
  (0, 437)	1
  (0, 9702)	1
  (0, 5375)	1
  (0, 8563)	1
  (0, 1851)	1
  (0, 248)	1
  (0, 4612)	1
  (0, 4545)	1
  :	:
  (9999, 2153)	1
  (9999, 5975)	1
  (9999, 3508)	1
  (9999, 9020)	1
  (9999, 212)	1
  (9999, 6520)	1
  (9999, 5718)	1
  (9999, 6248)	1
  (9999, 3800)	1
  (9999, 7968)	1
  (9999, 5066)	1
  (9999, 310)	1
  (9999, 4980)	1
  (9999, 5717)	1
  (9999, 9467)	1
  (9999, 1502)	1
  (9999, 1482)	1
  (9999, 6790)	1
  (9999, 5950)	1
  (9999, 2049)	1
  (9999, 2805)	1
  (9999, 1691)	1
  (9999, 9180)	1
  (9999, 6569)	1
  (9999, 4768)	2

KNN

In [13]:
knn = NearestNeighbors(n_neighbors=11, metric='cosine', algorithm='brute')
knn.fit(vector)
print("KNN recommendation model is ready.")

KNN recommendation model is ready.

Movie Recommendation System

In [14]:
def recommend(movie):
    try:
        movie_index = movies[movies['title'] == movie].index[0]
        movie_vector = vector[movie_index].reshape(1, -1)
        distances, indices = knn.kneighbors(movie_vector)
        distances = distances.flatten()
        indices = indices.flatten()
        print(f"Recommendations for '{movie}':")
        for i in range(1, len(indices)):
            recommended_movie_title = movies.iloc[indices[i]].title
            distance_score = distances[i]
            print(f"- {recommended_movie_title}")
    except IndexError:
            print(f"Movie '{movie}' not found in the dataset.")
movie_name = input("Enter The Name Of The Movie: ")
movie_list = movies['title'].tolist()
match = get_close_matches(movie_name, movie_list, n=1, cutoff=0.6)
if match:
    print(f"\nDid you mean: {match[0]}?")
    recommend(match[0])
else:
    print("Movie not found in the dataset.")

Movie not found in the dataset.

In [15]:
import pickle
pickle.dump(movies, open("movies.pkl", "wb"))
pickle.dump(vector, open("vector.pkl", "wb"))
pickle.dump(knn, open("knn.pkl", "wb"))

In [16]:
print(vector.shape)
print(type(vector))
print(len(movies))

(10000, 10000)
<class 'scipy.sparse._csr.csr_matrix'>
10000